project_id = "tpohsmxpcqqgxcgectfs"

[functions.chat-ai]
verify_jwt = true

[functions.add-admin]
verify_jwt = false

[functions.trial-chat]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-scheduled-insights]
verify_jwt = false
