import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { toast } from "@/hooks/use-toast";
import { Send, Save, Users, Loader2, Trash2, RefreshCw, ChevronDown, X, Sparkles, Wand2 } from "lucide-react";
import { format } from "date-fns";

type Activity = "" | "today" | "week" | "month" | "dormant";
type Credits = "" | "out" | "free_only" | "paid";

interface Filters {
  life_stage: string[];
  activity: Activity;
  most_active: number | null;
  cycle_phase: string[];
  timezone: string[];
  credits: Credits;
  participant_ids: string[];
}

interface Broadcast {
  id: string;
  title: string | null;
  content: string;
  segment_filters: any;
  status: string;
  recipient_count: number | null;
  sent_at: string | null;
  created_at: string;
}

interface ParticipantLite {
  id: string;
  full_name: string;
  email: string | null;
}

const LIFE_STAGES = ["cycling", "postpartum", "menopause"];
const PHASES = ["menstrual", "follicular", "ovulation", "luteal"];

const emptyFilters: Filters = {
  life_stage: [],
  activity: "",
  most_active: null,
  cycle_phase: [],
  timezone: [],
  credits: "",
  participant_ids: [],
};

export function NotificationsTab() {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [filters, setFilters] = useState<Filters>(emptyFilters);
  const [timezones, setTimezones] = useState<string[]>([]);
  const [participantsList, setParticipantsList] = useState<ParticipantLite[]>([]);
  const [participantSearch, setParticipantSearch] = useState("");
  const [previewCount, setPreviewCount] = useState<number | null>(null);
  const [isPreviewing, setIsPreviewing] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [drafts, setDrafts] = useState<Broadcast[]>([]);
  const [history, setHistory] = useState<Broadcast[]>([]);
  const [editingDraftId, setEditingDraftId] = useState<string | null>(null);

  // AI assist
  const [aiTopic, setAiTopic] = useState("");
  const [isDrafting, setIsDrafting] = useState(false);
  const [aiSuggestions, setAiSuggestions] = useState<
    Array<{ id: string; label: string; description: string; augmented_message: string }>
  >([]);
  const [baseAiMessage, setBaseAiMessage] = useState<string>("");
  const [activeSuggestionIds, setActiveSuggestionIds] = useState<string[]>([]);

  // CTA + conversation starters generated by AI (admin-editable)
  type CtaTab = "" | "home" | "ask" | "plan";
  type PlanSection = "" | "mood" | "exercise" | "nutrition";
  const [ctaLabel, setCtaLabel] = useState("");
  const [ctaTab, setCtaTab] = useState<CtaTab>("");
  const [ctaPlanSection, setCtaPlanSection] = useState<PlanSection>("");
  const [ctaHumanLabel, setCtaHumanLabel] = useState("");
  const [starters, setStarters] = useState<string[]>(["", "", ""]);

  const handleAiDraft = async () => {
    const topic = aiTopic.trim() || title.trim();
    if (!topic) {
      toast({ title: "Add a topic", description: "Type a short title or topic first.", variant: "destructive" });
      return;
    }
    setIsDrafting(true);
    try {
      const { data, error } = await supabase.functions.invoke("draft-broadcast", {
        body: { topic },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setBaseAiMessage(data.message);
      setContent(data.message);
      if (!title.trim() && data.title) setTitle(data.title);
      setAiSuggestions(data.suggestions ?? []);
      setActiveSuggestionIds([]);
      // Populate CTA + starters from AI
      const wtf = data.where_to_find ?? {};
      setCtaTab((wtf.tab as CtaTab) || "");
      setCtaPlanSection((wtf.plan_section as PlanSection) || "");
      setCtaHumanLabel(wtf.human_label || "");
      setCtaLabel(data.cta_label || "");
      const s = Array.isArray(data.conversation_starters) ? data.conversation_starters.slice(0, 3) : [];
      setStarters([s[0] ?? "", s[1] ?? "", s[2] ?? ""]);
      setPreviewCount(null);
    } catch (e: any) {
      toast({ title: "Draft failed", description: e.message, variant: "destructive" });
    } finally {
      setIsDrafting(false);
    }
  };

  const toggleSuggestion = (id: string) => {
    const next = activeSuggestionIds.includes(id)
      ? activeSuggestionIds.filter((x) => x !== id)
      : [...activeSuggestionIds, id];
    setActiveSuggestionIds(next);
    if (next.length === 0) {
      setContent(baseAiMessage);
    } else {
      const lastId = next[next.length - 1];
      const sug = aiSuggestions.find((s) => s.id === lastId);
      if (sug) setContent(sug.augmented_message);
    }
    setPreviewCount(null);
  };


  // Load distinct timezones + full participants list
  useEffect(() => {
    supabase
      .from("participants")
      .select("id, full_name, email, timezone")
      .eq("is_active", true)
      .order("full_name", { ascending: true })
      .then(({ data }) => {
        const rows = data ?? [];
        const unique = Array.from(
          new Set(rows.map((p) => p.timezone).filter(Boolean) as string[]),
        ).sort();
        setTimezones(unique);
        setParticipantsList(
          rows.map((p) => ({ id: p.id, full_name: p.full_name, email: p.email })),
        );
      });
    loadBroadcasts();
  }, []);

  const loadBroadcasts = async () => {
    const { data } = await supabase
      .from("admin_broadcasts")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(50);
    const all = (data ?? []) as Broadcast[];
    setDrafts(all.filter((b) => b.status === "draft"));
    setHistory(all.filter((b) => b.status === "sent"));
  };

  const buildPayload = (action: "preview" | "send") => {
    const cleanedStarters = starters.map((s) => s.trim()).filter(Boolean);
    const cta = ctaTab && ctaLabel.trim()
      ? {
          label: ctaLabel.trim(),
          tab: ctaTab,
          plan_section: ctaTab === "plan" ? (ctaPlanSection || null) : null,
        }
      : null;
    return {
      action,
      title: title.trim() || null,
      content: content.trim(),
      filters: {
        life_stage: filters.life_stage.length > 0 ? filters.life_stage : undefined,
        activity: filters.activity || undefined,
        most_active: filters.most_active || undefined,
        cycle_phase: filters.cycle_phase.length > 0 ? filters.cycle_phase : undefined,
        timezone: filters.timezone.length > 0 ? filters.timezone : undefined,
        credits: filters.credits || undefined,
        participant_ids: filters.participant_ids.length > 0 ? filters.participant_ids : undefined,
      },
      broadcast_id: editingDraftId ?? undefined,
      cta,
      conversation_starters: cleanedStarters.length > 0 ? cleanedStarters : null,
    };
  };

  const handlePreview = async () => {
    setIsPreviewing(true);
    setPreviewCount(null);
    try {
      const { data, error } = await supabase.functions.invoke("send-broadcast", {
        body: buildPayload("preview"),
      });
      if (error) throw error;
      setPreviewCount(data?.count ?? 0);
    } catch (e: any) {
      toast({ title: "Preview failed", description: e.message, variant: "destructive" });
    } finally {
      setIsPreviewing(false);
    }
  };

  const handleSend = async () => {
    if (!content.trim()) {
      toast({ title: "Message required", description: "Please write a message.", variant: "destructive" });
      return;
    }
    if (!confirm(`Send this message to ${previewCount ?? "?"} users? This cannot be undone.`)) return;
    setIsSending(true);
    try {
      const { data, error } = await supabase.functions.invoke("send-broadcast", {
        body: buildPayload("send"),
      });
      if (error) throw error;
      toast({ title: "Broadcast sent", description: `Delivered to ${data?.count ?? 0} users.` });
      resetForm();
      loadBroadcasts();
    } catch (e: any) {
      toast({ title: "Send failed", description: e.message, variant: "destructive" });
    } finally {
      setIsSending(false);
    }
  };

  const handleSaveDraft = async () => {
    if (!content.trim()) {
      toast({ title: "Message required", variant: "destructive" });
      return;
    }
    setIsSavingDraft(true);
    try {
      const { data: userData } = await supabase.auth.getUser();
      const payload = {
        title: title.trim() || null,
        content: content.trim(),
        segment_filters: buildPayload("preview").filters as any,
        status: "draft",
        created_by: userData.user!.id,
      };
      if (editingDraftId) {
        await supabase.from("admin_broadcasts").update(payload).eq("id", editingDraftId);
      } else {
        await supabase.from("admin_broadcasts").insert(payload);
      }
      toast({ title: "Draft saved" });
      resetForm();
      loadBroadcasts();
    } catch (e: any) {
      toast({ title: "Save failed", description: e.message, variant: "destructive" });
    } finally {
      setIsSavingDraft(false);
    }
  };

  const loadDraft = (d: Broadcast) => {
    setEditingDraftId(d.id);
    setTitle(d.title ?? "");
    setContent(d.content);
    const f = d.segment_filters || {};
    setFilters({
      life_stage: f.life_stage ?? [],
      activity: f.activity ?? "",
      most_active: f.most_active ?? null,
      cycle_phase: f.cycle_phase ?? [],
      timezone: f.timezone ?? [],
      credits: f.credits ?? "",
      participant_ids: f.participant_ids ?? [],
    });
    setPreviewCount(null);
  };

  const deleteDraft = async (id: string) => {
    if (!confirm("Delete this draft?")) return;
    await supabase.from("admin_broadcasts").delete().eq("id", id);
    if (editingDraftId === id) resetForm();
    loadBroadcasts();
  };

  const resetForm = () => {
    setEditingDraftId(null);
    setTitle("");
    setContent("");
    setFilters(emptyFilters);
    setPreviewCount(null);
    setCtaLabel("");
    setCtaTab("");
    setCtaPlanSection("");
    setCtaHumanLabel("");
    setStarters(["", "", ""]);
    setAiSuggestions([]);
    setActiveSuggestionIds([]);
    setBaseAiMessage("");
    setAiTopic("");
  };

  const toggleArr = (key: "life_stage" | "cycle_phase" | "timezone", val: string) => {
    setFilters((f) => ({
      ...f,
      [key]: f[key].includes(val) ? f[key].filter((x) => x !== val) : [...f[key], val],
    }));
    setPreviewCount(null);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Composer */}
      <div className="lg:col-span-2 space-y-6">
        <Card className="p-6 space-y-5">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-foreground">
              {editingDraftId ? "Editing draft" : "New notification"}
            </h3>
            {editingDraftId && (
              <Button variant="ghost" size="sm" onClick={resetForm}>
                <RefreshCw className="w-3 h-3 mr-1" /> New
              </Button>
            )}
          </div>

          {/* AI Assist */}
          <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 space-y-3">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-primary" />
              <Label className="text-sm font-semibold text-foreground">Draft with AI</Label>
            </div>
            <p className="text-xs text-muted-foreground">
              Type a topic (e.g. "Menu Builder launch") and Logan will draft the message and suggest enhancements.
            </p>
            <div className="flex flex-col sm:flex-row gap-2">
              <Input
                value={aiTopic}
                onChange={(e) => setAiTopic(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    handleAiDraft();
                  }
                }}
                placeholder="e.g. Menu Builder launch, Period reminder check-in..."
                className="flex-1"
              />
              <Button onClick={handleAiDraft} disabled={isDrafting} className="shrink-0">
                {isDrafting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Wand2 className="w-4 h-4 mr-2" />}
                Generate
              </Button>
            </div>

            {aiSuggestions.length > 0 && (
              <div className="space-y-2 pt-2 border-t border-primary/10">
                <p className="text-xs font-medium text-foreground">Smart enhancements — toggle to apply:</p>
                <div className="space-y-1.5">
                  {aiSuggestions.map((s) => {
                    const active = activeSuggestionIds.includes(s.id);
                    return (
                      <button
                        key={s.id}
                        type="button"
                        onClick={() => toggleSuggestion(s.id)}
                        className={`w-full text-left rounded-md border p-2.5 transition-colors ${
                          active
                            ? "bg-primary/15 border-primary/40"
                            : "bg-background/50 border-border hover:border-primary/30"
                        }`}
                      >
                        <div className="flex items-start gap-2">
                          <Checkbox checked={active} className="mt-0.5 pointer-events-none" />
                          <div className="flex-1 min-w-0">
                            <p className="text-xs font-medium text-foreground">{s.label}</p>
                            <p className="text-[11px] text-muted-foreground mt-0.5">{s.description}</p>
                          </div>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>

          <div className="space-y-2">
            <Label>Title (internal — not shown to users)</Label>
            <Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Menu Builder launch" />
          </div>

          <div className="space-y-2">
            <Label>Message (sent as Logan in the user's chat)</Label>
            <Textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Hey! I just added a new Menu Builder under your Plan tab..."
              rows={5}
            />
          </div>

          {/* Filters */}
          <div className="space-y-4 pt-2 border-t border-border">
            <h4 className="text-sm font-semibold text-foreground">Segment filters</h4>

            {/* Specific users — overrides other filters when used */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-xs text-muted-foreground">
                  Specific users {filters.participant_ids.length > 0 && (
                    <span className="text-primary">
                      ({filters.participant_ids.length} selected — overrides other filters)
                    </span>
                  )}
                </Label>
                {filters.participant_ids.length > 0 && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-6 text-xs"
                    onClick={() => {
                      setFilters((f) => ({ ...f, participant_ids: [] }));
                      setPreviewCount(null);
                    }}
                  >
                    Clear
                  </Button>
                )}
              </div>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    role="combobox"
                    className="w-full justify-between font-normal"
                  >
                    <span className={filters.participant_ids.length === 0 ? "text-muted-foreground" : ""}>
                      {filters.participant_ids.length === 0
                        ? "Select specific users"
                        : `${filters.participant_ids.length} user${filters.participant_ids.length === 1 ? "" : "s"} selected`}
                    </span>
                    <ChevronDown className="w-4 h-4 opacity-50 shrink-0 ml-2" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent
                  className="w-[--radix-popover-trigger-width] p-0"
                  align="start"
                >
                  <div className="p-2 border-b border-border">
                    <Input
                      placeholder="Search by name or email..."
                      value={participantSearch}
                      onChange={(e) => setParticipantSearch(e.target.value)}
                      className="h-8"
                    />
                  </div>
                  <ScrollArea className="h-64">
                    <div className="p-1">
                      {participantsList.length === 0 && (
                        <p className="text-xs text-muted-foreground p-3">Loading users...</p>
                      )}
                      {participantsList
                        .filter((p) => {
                          const q = participantSearch.toLowerCase().trim();
                          if (!q) return true;
                          return (
                            p.full_name?.toLowerCase().includes(q) ||
                            p.email?.toLowerCase().includes(q)
                          );
                        })
                        .slice(0, 100)
                        .map((p) => {
                          const checked = filters.participant_ids.includes(p.id);
                          return (
                            <label
                              key={p.id}
                              className="flex items-center gap-2 text-sm cursor-pointer hover:bg-muted/50 rounded px-2 py-1.5"
                            >
                              <Checkbox
                                checked={checked}
                                onCheckedChange={() => {
                                  setFilters((f) => ({
                                    ...f,
                                    participant_ids: checked
                                      ? f.participant_ids.filter((x) => x !== p.id)
                                      : [...f.participant_ids, p.id],
                                  }));
                                  setPreviewCount(null);
                                }}
                              />
                              <span className="text-foreground truncate flex-1 min-w-0">
                                {p.full_name}
                                <span className="text-muted-foreground ml-1 text-xs">
                                  {p.email}
                                </span>
                              </span>
                            </label>
                          );
                        })}
                    </div>
                  </ScrollArea>
                </PopoverContent>
              </Popover>

              {filters.participant_ids.length > 0 && (
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {filters.participant_ids.map((id) => {
                    const p = participantsList.find((x) => x.id === id);
                    if (!p) return null;
                    return (
                      <Badge
                        key={id}
                        variant="secondary"
                        className="gap-1 pr-1 font-normal"
                      >
                        {p.full_name}
                        <button
                          type="button"
                          onClick={() => {
                            setFilters((f) => ({
                              ...f,
                              participant_ids: f.participant_ids.filter((x) => x !== id),
                            }));
                            setPreviewCount(null);
                          }}
                          className="hover:bg-muted rounded-sm p-0.5"
                          aria-label={`Remove ${p.full_name}`}
                        >
                          <X className="w-3 h-3" />
                        </button>
                      </Badge>
                    );
                  })}
                </div>
              )}
            </div>

            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground">Life stage</Label>
              <div className="flex flex-wrap gap-2">
                {LIFE_STAGES.map((s) => (
                  <Badge
                    key={s}
                    variant={filters.life_stage.includes(s) ? "default" : "outline"}
                    className="cursor-pointer capitalize"
                    onClick={() => toggleArr("life_stage", s)}
                  >
                    {s}
                  </Badge>
                ))}
              </div>
            </div>

            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground">Current cycle phase</Label>
              <div className="flex flex-wrap gap-2">
                {PHASES.map((p) => (
                  <Badge
                    key={p}
                    variant={filters.cycle_phase.includes(p) ? "default" : "outline"}
                    className="cursor-pointer capitalize"
                    onClick={() => toggleArr("cycle_phase", p)}
                  >
                    {p}
                  </Badge>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label className="text-xs text-muted-foreground">Activity</Label>
                <Select
                  value={filters.activity}
                  onValueChange={(v) => {
                    setFilters((f) => ({ ...f, activity: v as Activity }));
                    setPreviewCount(null);
                  }}
                >
                  <SelectTrigger><SelectValue placeholder="Any activity" /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="today">Active today</SelectItem>
                    <SelectItem value="week">Active this week</SelectItem>
                    <SelectItem value="month">Active last 30 days</SelectItem>
                    <SelectItem value="dormant">Dormant 30+ days</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label className="text-xs text-muted-foreground">Credits</Label>
                <Select
                  value={filters.credits}
                  onValueChange={(v) => {
                    setFilters((f) => ({ ...f, credits: v as Credits }));
                    setPreviewCount(null);
                  }}
                >
                  <SelectTrigger><SelectValue placeholder="Any credits" /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="out">Out of credits</SelectItem>
                    <SelectItem value="free_only">Free tier only</SelectItem>
                    <SelectItem value="paid">Paid users</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground">
                Top N most active users (last 30 days)
              </Label>
              <Input
                type="number"
                min={0}
                value={filters.most_active ?? ""}
                onChange={(e) => {
                  const v = e.target.value ? parseInt(e.target.value) : null;
                  setFilters((f) => ({ ...f, most_active: v }));
                  setPreviewCount(null);
                }}
                placeholder="e.g. 10"
              />
            </div>

            {timezones.length > 0 && (
              <div className="space-y-2">
                <Label className="text-xs text-muted-foreground">Timezone (proxy for country)</Label>
                <ScrollArea className="h-32 rounded-md border border-border p-2">
                  <div className="space-y-1">
                    {timezones.map((tz) => (
                      <label key={tz} className="flex items-center gap-2 text-sm cursor-pointer">
                        <Checkbox
                          checked={filters.timezone.includes(tz)}
                          onCheckedChange={() => toggleArr("timezone", tz)}
                        />
                        <span className="text-foreground">{tz}</span>
                      </label>
                    ))}
                  </div>
                </ScrollArea>
              </div>
            )}
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-2 pt-4 border-t border-border">
            <Button onClick={handlePreview} variant="outline" disabled={isPreviewing} className="flex-1">
              {isPreviewing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Users className="w-4 h-4 mr-2" />}
              Preview audience
            </Button>
            <Button onClick={handleSaveDraft} variant="outline" disabled={isSavingDraft} className="flex-1">
              {isSavingDraft ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
              Save draft
            </Button>
            <Button onClick={handleSend} disabled={isSending || previewCount === null} className="flex-1">
              {isSending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
              Send {previewCount !== null ? `(${previewCount})` : ""}
            </Button>
          </div>

          {previewCount !== null && (
            <div className="rounded-lg bg-primary/10 border border-primary/20 p-3 text-sm text-foreground">
              <strong>{previewCount}</strong> user{previewCount === 1 ? "" : "s"} match this segment.
              {previewCount === 0 && " Adjust filters and re-preview."}
            </div>
          )}
        </Card>
      </div>

      {/* Sidebar: drafts + history */}
      <div className="space-y-6">
        <Card className="p-4">
          <h4 className="text-sm font-semibold text-foreground mb-3">Drafts ({drafts.length})</h4>
          <div className="space-y-2">
            {drafts.length === 0 && (
              <p className="text-xs text-muted-foreground">No drafts yet.</p>
            )}
            {drafts.map((d) => (
              <div key={d.id} className="rounded-lg border border-border p-2 space-y-1">
                <p className="text-xs font-medium text-foreground line-clamp-1">
                  {d.title || d.content.slice(0, 40)}
                </p>
                <p className="text-[10px] text-muted-foreground line-clamp-2">{d.content}</p>
                <div className="flex gap-1">
                  <Button size="sm" variant="ghost" onClick={() => loadDraft(d)} className="text-xs h-7">
                    Edit
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => deleteDraft(d.id)} className="text-xs h-7 text-destructive">
                    <Trash2 className="w-3 h-3" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </Card>

        <Card className="p-4">
          <h4 className="text-sm font-semibold text-foreground mb-3">Sent history</h4>
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {history.length === 0 && (
              <p className="text-xs text-muted-foreground">Nothing sent yet.</p>
            )}
            {history.map((h) => (
              <div key={h.id} className="rounded-lg border border-border p-2 space-y-1">
                <div className="flex items-center justify-between">
                  <p className="text-xs font-medium text-foreground line-clamp-1">
                    {h.title || h.content.slice(0, 30)}
                  </p>
                  <Badge variant="secondary" className="text-[10px]">
                    {h.recipient_count ?? 0}
                  </Badge>
                </div>
                <p className="text-[10px] text-muted-foreground">
                  {h.sent_at ? format(new Date(h.sent_at), "MMM d, h:mm a") : ""}
                </p>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
}
